development:
  adapter: postgresql
  encoding: unicode
  database: linkcapital_development
  pool: 5
  username: earlynovrock
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: linkcapital_test
  pool: 5
  username: earlynovrock
  password: