development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://linkfayeserver.herokuapp.com/faye"
  secret_token: "link2013"
  signature_expiration: 86400 # one day